name: Publicar Pagina a Surge.sh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: configura nodejs  
        uses: actions/setup-node@v3
        with:
            node-version: '18' 

      - name: Instala Surge       
        run: npm install --global surge

      - name: Publicar pagina
        run: surge --project ./ --domain https://alexcordero.surge.sh ${{ secrets.SURGE_DOMAIN }} --token   2615166d58f40920e188af3d600f9206  ${{ secrets.SURGE_API_KEY }}